TodoList.find_or_create_by(name: 'Setup Rails Application')
TodoList.find_or_create_by(name: 'Setup Docker PG database')
TodoList.find_or_create_by(name: 'find_or_create_by todo_lists table')
TodoList.find_or_create_by(name: 'find_or_create_by TodoList model')
controller = TodoList.find_or_create_by(name: 'find_or_create_by TodoList controller')
controller.todo_items.find_or_create_by(title: 'Name it', description: 'first step', completion: 1.days.ago)